### ISSUE TITLE
Multiple object?

### ISSUE THREAD

**Issue by Turtleted21** [AdaRoseCannon/aframe-surface-scatter#2]
Hello
Is it possible to have multiple object on the same surface?
or perhaps multiple surface-scatter like multiple animation in aframe:
` surface-scatter="object:#decoration_cube.....";  surface-scatter__name="object:#decoration_sphere.....";`

Thanks

**Comment by AdaRoseCannon** [comment]
Not right now but that shouldn't be too hard to add.

**Comment by AdaRoseCannon** [comment]
I just checked the code, I already set that up.

Yes you can do multiple like the animation by appending `__name`

**Comment by AdaRoseCannon** [comment]
Let me know if it doesn't work, closing for now.

**Comment by Turtleted21** [comment]
it doesn't work, the first surface-scatter is loaded, then when the second surface-scatter is loaded the fisrt disappear.

surface-scatter__cube="object:#decoration_cube;count:500;scale:1 1 1;scaleJitter:2 2 2;uniformJitter:false;"
surface-scatter__grass="object:#decoration_grass;count:10000;scale:1 1 1;scaleJitter:2 2 2;uniformJitter:true;"

**Comment by AdaRoseCannon** [comment]
Alright I'll investigate, thanks for trying it out.

**Comment by AdaRoseCannon** [comment]
Fixed
